{% set name = "geeet" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kaust-halo/geeet/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3ce4da6de2cd6fc18325d1e879f747ff0677f4f9acf1be73a8ffac1eeda57f78

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - geeet

about:
  home: https://github.com/kaust-halo/geeet
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Evapotranspiration (ET) models for use in python and with integration into Google Earth Engine.
  doc_url: https://kaust-halo.github.io/geeet
  dev_url: https://github.com/kaust-halo/geeet

extra:
  recipe-maintainers:
    - lopezvoliver
